const ExcelJS = require('exceljs');

function addUnifiedFooter(ws, colCount) {
  const footerRow1 = ws.addRow(['']).number;
  ws.mergeCells(footerRow1, 1, footerRow1, colCount);
  const cell1 = ws.getCell(footerRow1, 1);
  cell1.value = 'Generated by AgriCatch Platform';
  cell1.font = { size: 10, italic: true };
  cell1.alignment = { horizontal: 'center' };

  const footerRow2 = ws.addRow(['']).number;
  ws.mergeCells(footerRow2, 1, footerRow2, colCount);
  const cell2 = ws.getCell(footerRow2, 1);
  cell2.value = 'Copyright © 2026 AgriCatch. All rights reserved.';
  cell2.font = { size: 10, italic: true };
  cell2.alignment = { horizontal: 'center' };

  return footerRow1;
}

async function main() {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet('Test');

  // Add some data with 5 columns
  ws.addRow(['A', 'B', 'C', 'D', 'E']);
  ws.addRow([1, 2, 3, 4, 5]);

  addUnifiedFooter(ws, 5);

  await wb.xlsx.writeFile('test_footer.xlsx');

  // Read back
  const wb2 = new ExcelJS.Workbook();
  await wb2.xlsx.readFile('test_footer.xlsx');
  const ws2 = wb2.worksheets[0];
  console.log('Merges:', Object.keys(ws2._merges));
  const lastRow = ws2.rowCount;
  for (let r = lastRow - 2; r <= lastRow; r++) {
    const row = [];
    for (let c = 1; c <= ws2.columnCount; c++) {
      const v = ws2.getCell(r, c).value;
      row.push(v === null ? 'null' : (v === '' ? '""' : v));
    }
    console.log(`Row ${r}:`, row.join(' | '));
  }
}

main();
