ALTER TABLE user_addresses ADD COLUMN IF NOT EXISTS province VARCHAR(100);
ALTER TABLE user_addresses ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE user_addresses ADD COLUMN IF NOT EXISTS barangay VARCHAR(100);
ALTER TABLE user_addresses ADD COLUMN IF NOT EXISTS street TEXT;